import React from 'react';
import { Student, Score, SCORE_OPTIONS } from '../types';
import { generateDeskripsi } from '../utils';
import { Plus, Trash2, Wand2 } from 'lucide-react';
import { SURAHS } from '../data/surahs';

interface DataTableProps {
    students: Student[];
    onUpdate: (id: string, updates: Partial<Student>) => void;
    onAdd: () => void;
    onDelete: (id: string) => void;
}

export function DataTable({ students, onUpdate, onAdd, onDelete }: DataTableProps) {
    const handleScoreChange = (id: string, field: keyof Student, value: Score) => {
        onUpdate(id, { [field]: value });
    };

    const handleTextChange = (id: string, field: keyof Student, value: string) => {
        onUpdate(id, { [field]: value });
    };

    const autoGenerateDescription = (id: string, student: Student) => {
        const desc = generateDeskripsi(student);
        onUpdate(id, { deskripsi: desc });
    };

    const autoGenerateAllDescriptions = () => {
        students.forEach(student => {
            onUpdate(student.id, { deskripsi: generateDeskripsi(student) });
        });
    };

    return (
        <div className="flex flex-1 overflow-hidden font-sans">
            <aside className="w-64 border-r border-[#1A1A1A] p-6 flex flex-col gap-8 bg-[#FAF9F6] shrink-0 overflow-y-auto">
              <section>
                <h2 className="text-xs font-bold uppercase tracking-widest mb-4 opacity-50 border-b border-[#1A1A1A] pb-2">Parameter Penilaian</h2>
                <div className="space-y-3">
                  <div className="flex justify-between items-center text-sm">
                    <span className="bg-green-100 text-green-800 font-bold px-2 py-0.5 border border-[#1A1A1A]">SB</span>
                    <span className="font-bold">Sangat Baik</span>
                  </div>
                  <div className="flex justify-between items-center text-sm">
                    <span className="bg-blue-100 text-blue-800 font-bold px-2 py-0.5 border border-[#1A1A1A]">B</span>
                    <span className="font-bold">Baik</span>
                  </div>
                  <div className="flex justify-between items-center text-sm">
                    <span className="bg-yellow-100 text-yellow-800 font-bold px-2 py-0.5 border border-[#1A1A1A]">C</span>
                    <span className="font-bold">Cukup</span>
                  </div>
                  <div className="flex justify-between items-center text-sm">
                    <span className="bg-red-100 text-red-800 font-bold px-2 py-0.5 border border-[#1A1A1A]">PB</span>
                    <span className="font-bold">Perlu Bimbingan</span>
                  </div>
                </div>
              </section>

              <section className="mt-auto">
                <div className="p-4 border border-[#1A1A1A] border-dashed text-xs italic tracking-wide leading-relaxed bg-white shadow-sm">
                  "Rumus deskripsi otomatis aktif berdasarkan Capaian Pembelajaran (CP) yang dipilih. Klik auto-generate untuk mengisi."
                </div>
              </section>
            </aside>

            <div className="flex-1 flex flex-col min-w-0 bg-white">
                <div className="p-6 border-b border-[#1A1A1A] flex justify-between items-center shrink-0">
                    <h3 className="text-sm font-bold uppercase tracking-widest">Input Data Siswa & Catatan Guru</h3>
                    <div className="flex gap-4 text-xs font-semibold tracking-widest">
                        <button 
                            onClick={onAdd}
                            className="flex items-center gap-2 bg-[#1A1A1A] border border-[#1A1A1A] hover:bg-black text-white px-4 py-2 uppercase transition-colors"
                        >
                            <Plus className="w-4 h-4" /> Tambah Siswa
                        </button>
                    </div>
                </div>

                <div className="flex-1 overflow-auto relative p-4">
                    <table className="w-max min-w-full text-left border-collapse text-[11px] font-sans border-2 border-[#1A1A1A]">
                        <thead className="bg-[#FAF9F6] sticky top-0 z-10 uppercase tracking-wider font-bold">
                            <tr className="border-b border-[#1A1A1A]">
                                <th rowSpan={2} className="border-r border-[#1A1A1A] p-2 text-center w-12 border-b border-b-[#1A1A1A]">NO</th>
                                <th rowSpan={2} className="border-r border-[#1A1A1A] p-2 text-center border-b border-b-[#1A1A1A]">NO. Induk</th>
                                <th rowSpan={2} className="border-r border-[#1A1A1A] p-2 text-center border-b border-b-[#1A1A1A]">NISN</th>
                                <th rowSpan={2} className="border-r border-[#1A1A1A] p-2 min-w-[200px] border-b border-b-[#1A1A1A]">NAMA PESERTA</th>
                                <th colSpan={4} className="border-r border-b border-[#1A1A1A] p-2 text-center bg-green-50">Capaian Kompetensi Baca Al-Quran</th>
                                <th colSpan={3} className="border-r border-b border-[#1A1A1A] p-2 text-center bg-blue-50">Capaian Kompetensi Tulis Al-Qur'an</th>
                                <th colSpan={5} className="border-r border-b border-[#1A1A1A] p-2 text-center bg-yellow-50">Capaian Hafalan Al-Qur'an</th>
                                <th colSpan={5} className="border-r border-b border-[#1A1A1A] p-2 text-center bg-purple-50">Perkembangan Karakter Religius</th>
                                <th rowSpan={2} className="border-r border-[#1A1A1A] p-2 text-center min-w-[300px] border-b border-b-[#1A1A1A]">Deskripsi Perkembangan Peserta Didik</th>
                                <th rowSpan={2} className="border-r border-[#1A1A1A] p-2 text-center min-w-[200px] border-b border-b-[#1A1A1A]">Catatan</th>
                                <th rowSpan={2} className="p-2 text-center border-b border-b-[#1A1A1A]">Aksi</th>
                            </tr>
                            <tr className="bg-[#F4F1EA] text-[10px] text-center border-b border-[#1A1A1A]">
                                {/* Baca */}
                                <th className="border-r border-[#1A1A1A] p-1 w-24 whitespace-normal">Ketepatan makhraj huruf</th>
                                <th className="border-r border-[#1A1A1A] p-1 w-24 whitespace-normal">Penerapan hukum tajwid</th>
                                <th className="border-r border-[#1A1A1A] p-1 w-24 whitespace-normal">Kelancaran membaca</th>
                                <th className="border-r border-[#1A1A1A] p-1 w-24 whitespace-normal">Kemandirian membaca</th>
                                {/* Tulis */}
                                <th className="border-r border-[#1A1A1A] p-1 w-24 whitespace-normal">Ketepatan penulisan huruf hijaiyah</th>
                                <th className="border-r border-[#1A1A1A] p-1 w-24 whitespace-normal">Kerapihan tulisan</th>
                                <th className="border-r border-[#1A1A1A] p-1 w-24 whitespace-normal">Ketepatan menyalin lafadz</th>
                                {/* Hafalan */}
                                <th className="border-r border-[#1A1A1A] p-1 min-w-[120px]">Target Hafalan</th>
                                <th className="border-r border-[#1A1A1A] p-1 min-w-[120px]">Hafalan Dicapai</th>
                                <th className="border-r border-[#1A1A1A] p-1 w-24 whitespace-normal">Kelancaran Hafalan</th>
                                <th className="border-r border-[#1A1A1A] p-1 w-24 whitespace-normal">Konsistensi Muroja'ah</th>
                                <th className="border-r border-[#1A1A1A] p-1 min-w-[150px]">Catatan Hafalan</th>
                                {/* Karakter */}
                                <th className="border-r border-[#1A1A1A] p-1 w-20 whitespace-normal">Disiplin</th>
                                <th className="border-r border-[#1A1A1A] p-1 w-20 whitespace-normal">Adab kpd guru</th>
                                <th className="border-r border-[#1A1A1A] p-1 w-20 whitespace-normal">Sering beribadah</th>
                                <th className="border-r border-[#1A1A1A] p-1 w-20 whitespace-normal">Tgjwb & jujur</th>
                                <th className="border-r border-[#1A1A1A] p-1 w-20 whitespace-normal">Akhlak kpd teman</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-[#1A1A1A]">
                            {students.map((student, index) => (
                                <tr key={student.id} className="hover:bg-gray-50 bg-white">
                                    <td className="border-r border-[#1A1A1A] text-center font-bold font-serif">{student.urut}</td>
                                    <td className="border-r border-[#1A1A1A] p-0 border-b border-b-transparent">
                                        <input value={student.nisn} onChange={e => handleTextChange(student.id, 'nisn', e.target.value)} className="w-full h-full min-h-[32px] px-2 py-1 flex items-center outline-none text-center bg-transparent" />
                                    </td>
                                    <td className="border-r border-[#1A1A1A] p-0 border-b border-b-transparent">
                                        <input value={student.nis} onChange={e => handleTextChange(student.id, 'nis', e.target.value)} className="w-full h-full min-h-[32px] px-2 py-1 flex items-center outline-none text-center bg-transparent" />
                                    </td>
                                    <td className="border-r border-[#1A1A1A] p-0 font-bold uppercase border-b border-b-transparent">
                                        <input value={student.nama} onChange={e => handleTextChange(student.id, 'nama', e.target.value)} className="w-full h-full min-h-[32px] px-2 py-1 flex items-center outline-none font-bold bg-transparent uppercase text-[#1A1A1A]" />
                                    </td>
                                    
                                    {/* Baca */}
                                    <DropdownCell value={student.baca_makhraj} onChange={(v) => handleScoreChange(student.id, 'baca_makhraj', v)} />
                                    <DropdownCell value={student.baca_tajwid} onChange={(v) => handleScoreChange(student.id, 'baca_tajwid', v)} />
                                    <DropdownCell value={student.baca_lancar} onChange={(v) => handleScoreChange(student.id, 'baca_lancar', v)} />
                                    <DropdownCell value={student.baca_mandiri} onChange={(v) => handleScoreChange(student.id, 'baca_mandiri', v)} />

                                    {/* Tulis */}
                                    <DropdownCell value={student.tulis_hijaiyah} onChange={(v) => handleScoreChange(student.id, 'tulis_hijaiyah', v)} />
                                    <DropdownCell value={student.tulis_rapi} onChange={(v) => handleScoreChange(student.id, 'tulis_rapi', v)} />
                                    <DropdownCell value={student.tulis_salin} onChange={(v) => handleScoreChange(student.id, 'tulis_salin', v)} />

                                    {/* Hafal */}
                                    <td className="border-r border-[#1A1A1A] p-0 border-b border-b-transparent align-middle">
                                        <select 
                                            value={student.hafal_target} 
                                            onChange={e => {
                                                handleTextChange(student.id, 'hafal_target', e.target.value);
                                                handleTextChange(student.id, 'hafal_capai', ''); // Reset capai when target changes
                                            }} 
                                            className="w-full h-full min-h-[32px] px-2 py-1 outline-none bg-transparent font-serif overflow-hidden text-ellipsis cursor-pointer focus:bg-[#E5E7EB]/50"
                                        >
                                            <option value="">- Pilih Surah -</option>
                                            {SURAHS.map(s => (
                                                <option key={s.id} value={s.name}>{s.name} ({s.ayat} Ayat)</option>
                                            ))}
                                        </select>
                                    </td>
                                    <td className="border-r border-[#1A1A1A] p-0 border-b border-b-transparent align-middle">
                                        <select 
                                            value={student.hafal_capai} 
                                            onChange={e => handleTextChange(student.id, 'hafal_capai', e.target.value)} 
                                            className="w-full h-full min-h-[32px] px-2 py-1 outline-none bg-transparent font-bold font-serif cursor-pointer focus:bg-[#E5E7EB]/50 disabled:opacity-50"
                                            disabled={!student.hafal_target}
                                        >
                                            <option value="">- Ayat -</option>
                                            {(() => {
                                                const selSurah = SURAHS.find(s => s.name === student.hafal_target);
                                                if (!selSurah) return null;
                                                return Array.from({ length: selSurah.ayat }).map((_, i) => (
                                                    <option key={i+1} value={`${i+1}`}>{i+1} Ayat</option>
                                                ));
                                            })()}
                                        </select>
                                    </td>
                                    <DropdownCell value={student.hafal_lancar} onChange={(v) => handleScoreChange(student.id, 'hafal_lancar', v)} />
                                    <DropdownCell value={student.hafal_konsisten} onChange={(v) => handleScoreChange(student.id, 'hafal_konsisten', v)} />
                                    <td className="border-r border-[#1A1A1A] p-0 border-b border-b-transparent">
                                        <input value={student.hafal_catatan} onChange={e => handleTextChange(student.id, 'hafal_catatan', e.target.value)} className="w-full h-full min-h-[32px] px-2 py-1 text-[10px] flex items-center outline-none bg-transparent italic font-serif" placeholder="Manual..."/>
                                    </td>

                                    {/* Karakter */}
                                    <DropdownCell value={student.karakter_disiplin} onChange={(v) => handleScoreChange(student.id, 'karakter_disiplin', v)} />
                                    <DropdownCell value={student.karakter_adab} onChange={(v) => handleScoreChange(student.id, 'karakter_adab', v)} />
                                    <DropdownCell value={student.karakter_sungguh} onChange={(v) => handleScoreChange(student.id, 'karakter_sungguh', v)} />
                                    <DropdownCell value={student.karakter_tanggung} onChange={(v) => handleScoreChange(student.id, 'karakter_tanggung', v)} />
                                    <DropdownCell value={student.karakter_akhlak} onChange={(v) => handleScoreChange(student.id, 'karakter_akhlak', v)} />

                                    {/* Deskripsi */}
                                    <td className="border-r border-[#1A1A1A] p-0 relative group bg-[#FAF9F6]">
                                        <textarea 
                                            value={student.deskripsi} 
                                            onChange={e => handleTextChange(student.id, 'deskripsi', e.target.value)} 
                                            className="w-full h-full min-h-[64px] px-3 py-2 outline-none text-[11px] resize-y bg-transparent italic leading-relaxed font-serif text-[#1A1A1A]" 
                                        />
                                        <button 
                                            onClick={() => autoGenerateDescription(student.id, student)}
                                            className="absolute right-2 top-2 text-gray-500 hover:text-black opacity-0 group-hover:opacity-100 transition-opacity bg-white border border-[#1A1A1A] rounded p-1 shadow-sm"
                                            title="Auto Generate Deskripsi"
                                        >
                                            <Wand2 className="w-4 h-4" />
                                        </button>
                                    </td>
                                    {/* Catatan Umum */}
                                    <td className="border-r border-[#1A1A1A] p-0 border-b border-b-transparent">
                                        <textarea value={student.catatan} onChange={e => handleTextChange(student.id, 'catatan', e.target.value)} className="w-full h-full min-h-[64px] px-2 py-2 outline-none bg-transparent font-serif text-[11px]" />
                                    </td>
                                    {/* Aksi */}
                                    <td className="p-0 text-center px-2">
                                        <button onClick={() => onDelete(student.id)} className="text-[#1A1A1A] hover:text-red-700 p-1 transition-colors" title="Hapus Siswa">
                                            <Trash2 className="w-4 h-4" />
                                        </button>
                                    </td>
                                </tr>
                            ))}
                            {students.length === 0 && (
                                <tr>
                                    <td colSpan={25} className="text-center py-12 text-gray-400 font-sans uppercase tracking-widest hidden-table-empty">Belum ada data peserta didik.</td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
}

function DropdownCell({ value, onChange }: { value: Score, onChange: (val: Score) => void }) {
    const bgClass = value === 'SB' ? 'bg-green-100/50' : 
                    value === 'B' ? 'bg-blue-100/50' : 
                    value === 'C' ? 'bg-yellow-100/50' : 
                    value === 'PB' ? 'bg-red-100' : 'bg-transparent';
    const textClass = value === 'PB' ? 'text-red-800 font-bold' : 'font-bold';

    return (
        <td className={`border-r border-[#1A1A1A] p-0 w-16 ${bgClass} border-b border-b-transparent align-middle`}>
            <select 
                value={value} 
                onChange={(e) => onChange(e.target.value as Score)}
                className={`w-full h-full min-h-[32px] text-center outline-none py-1 appearance-none cursor-pointer bg-transparent uppercase font-sans ${textClass}`}
            >
                {SCORE_OPTIONS.map(opt => (
                    <option key={opt} value={opt}>{opt}</option>
                ))}
            </select>
        </td>
    );
}
